server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://192.168.31.61:3306/gmall_product?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
#logging:
#  level:
#    com.atguigu.gmall.product.mapper: debug

minio:
  endpointUrl: http://192.168.31.61:9000
  accessKey: admin
  secreKey: admin123456
  bucketName: gmall